// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    'reference/packet-composition',
    {
      type: 'category',
      label: 'Protocol',
      link: {type: 'doc', id: 'protocol/packet-catalog'},
      items: [{type: 'autogenerated', dirName: 'protocol'}],
    },
  ],
}

export default sidebars
